openapi: 3.0.0
info:
  title: Preprocessor server
  description: This is a simple API
  contact:
    email: mipt@mipt.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/MIPT-2PC/preprocessor/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: api
  description: operate 2 numbers
paths:
  /operate:
    post:
      tags:
      - api
      summary: operate 2 numbers
      description: operate 2 numbers with defined action
      operationId: operate
      requestBody:
        $ref: '#/components/requestBodies/Nums'
      responses:
        "200":
          description: Success computation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Nums'
                x-content-type: application/json
        "400":
          description: Invalid input
        "500":
          description: Computation Error
      x-openapi-router-controller: swagger_server.controllers.api_controller
  /results:
    get:
      tags:
      - api
      summary: Get previous results
      description: retrieve results
      operationId: get_results
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
                x-content-type: application/json
        "404":
          description: No data
      x-openapi-router-controller: swagger_server.controllers.api_controller
components:
  schemas:
    Results:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 13
        input:
          type: string
          example: 12+1
      example:
        result: 13
        input: 12+1
    Nums:
      required:
      - num1
      - num2
      - operation
      type: object
      properties:
        num1:
          type: number
          format: double
          example: 12
        num2:
          type: number
          format: double
          example: 1
        operation:
          type: string
          description: Types of operations
          example: +
          enum:
          - +
          - "-"
          - '*'
      example:
        num1: 12
        operation: +
        num2: 1
  requestBodies:
    Nums:
      description: Nums request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Nums'

