# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Table(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, payload: object=None):  # noqa: E501
        """Table - a model defined in Swagger

        :param payload: The payload of this Table.  # noqa: E501
        :type payload: object
        """
        self.swagger_types = {
            'payload': object
        }

        self.attribute_map = {
            'payload': 'payload'
        }
        self._payload = payload

    @classmethod
    def from_dict(cls, dikt) -> 'Table':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Table of this Table.  # noqa: E501
        :rtype: Table
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payload(self) -> object:
        """Gets the payload of this Table.


        :return: The payload of this Table.
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload: object):
        """Sets the payload of this Table.


        :param payload: The payload of this Table.
        :type payload: object
        """

        self._payload = payload
